### ISSUE TITLE
Locale per defecte

### ISSUE THREAD

**Issue by santich-dgtic** [GovernIB/pluginsib-validatesignature#15]
A la classe AfirmaCxfValidateSignaturePlugin el mètode "TimeStampInfo[] parseTimeStamp(String xml)" parsetja els dates amb el locale per defecte quan en realitat son hores UTC, el que fa que se parsetgin amb un desfase horari incorrecte.

**Comment by anadal-fundaciobit** [comment]
Aplicar el següent parxe:

index e2e445e..668f8ba 100644
--- a/afirmacxf/src/main/java/org/fundaciobit/plugins/validatesignature/afirmacxf/AfirmaCxfValidateSignaturePlugin.java
+++ b/afirmacxf/src/main/java/org/fundaciobit/plugins/validatesignature/afirmacxf/AfirmaCxfValidateSignaturePlugin.java
@@ -12,6 +12,7 @@ import java.util.List;
 import java.util.Locale;
 import java.util.Map;
 import java.util.Properties;
+import java.util.TimeZone;
 import java.util.regex.Matcher;
 import java.util.regex.Pattern;
 import java.io.ByteArrayInputStream;
@@ -338,6 +339,7 @@ public class AfirmaCxfValidateSignaturePlugin extends AbstractValidateSignatureP
       TimeStampInfo tsi = new TimeStampInfo();
 
       try {
+       dateFormatTimeStamp.setTimeZone(TimeZone.getTimeZone("UTC"));
         tsi.setCreationTime(dateFormatTimeStamp.parse(m.group(1)));
       } catch (ParseException e) {
         // TODO Auto-generated catch block

**Comment by anadal-fundaciobit** [comment]
Solucionat.

**Comment by anadal-fundaciobit** [comment]
Actualitzada la la versió 2.0.3
